global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8888']

  - job_name: 'monitor-admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitor-admin:8088']

  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['users-service:8081']

  - job_name: 'subjects'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['subjects-service:8082']

  - job_name: 'registration'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['registration-service:8083']

