name: Java CI with Maven

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test Config Server
        run: |
          cd config-server
          mvn clean test

      - name: Build and Test Eureka Server
        run: |
          cd eureka-server
          mvn clean test

      - name: Build and Test Users Service
        run: |
          cd users
          mvn clean test

      - name: Build and Test Subjects Service
        run: |
          cd subjects
          mvn clean test

      - name: Build and Test Registration Service
        run: |
          cd registration
          mvn clean test

      - name: Build and Test Monitor Admin
        run: |
          cd monitor-admin
          mvn clean test

      - name: Generate Coverage Report
        run: |
          cd users && mvn jacoco:report
          cd ../subjects && mvn jacoco:report
          cd ../registration && mvn jacoco:report

      - name: Check Code Quality
        run: |
          cd users && mvn checkstyle:check
          cd ../subjects && mvn checkstyle:check
          cd ../registration && mvn checkstyle:check